name="aksell-tools"
pages_build_output_dir="dist"

[vars]
GITHUB_REPO="https://github.com/aksellsor/tools"
CLOUDFLARE_DASH="https://dash.cloudflare.com/781f2601c68594125b6b97567364d0d6/pages/view/tools"
NEW_AKSELL_TOOL="https://github.com/new?template_name=boilerplate&template_owner=aksellsor"
EDIT_HTML="https://github.com/aksellsor/tools/edit/main/index.html"
EDIT_LINKS="https://github.com/aksellsor/tools/edit/main/public/links.csv"
EDIT_MARKDOWN="https://github.com/aksellsor/tools/edit/main/public/readme.md"
EDIT_PENS="https://github.com/aksellsor/tools/edit/main/public/ui-pens.csv"

[worker]
compatibility_date = "2024-12-09"
compatibility_flags = ["streams_enable_constructors"]